 BaseURL = "https://www.cicadacreativemag.com/"
  languageCode = "en-us"
  defaultContentLanguage = "en"
  baseURL = "/"
  title = "Cicada Creative Magazine"
  relativeURLS = true

  [taxonomies]
  tag = "tags"

  [permalinks]
  post = "/:title/"
  issues = "/:sections[1:]/:title"

  [params]
  author = ""
  fullImage = ""
  description = "Stay Creative."
      
 [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]

  sectionPagesMenu = "main"
  [menu]
  [[menu.main]]
  name = "Home"
  url = "/landing"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
  [[menu.main]]
  name = "Issues"
  url = "/issues/"
  weight = 3
  [[menu.main]]
  name = "Submit"
  url = "/submit/"
  weight = 4
  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 5
  [[menu.main]]
  name = "Staff"
  url = "/staff/"
  weight = 6
  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
